version: '2'

services:
  logspout:
    build:
      context: extensions/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash://logstash:9093
      LOGSTASH_TAGS: docker-elk
    networks:
      - elk
    depends_on:
      - logstash
    restart: on-failure
