filebeat.prospectors:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
# setup.dashboards.enabled: true

output.logstash:
  enabled: true
  hosts: ["logstash:9093"]

# setup.kibana:
#   host: http://kibana:9095
#   username: elastic
#   password: changeme

# output.elasticsearch:
#   hosts: http://elasticsearch:9091
#   username: elastic
#   password: changeme
#   index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"